# Generated by Django 4.2.3 on 2025-06-13 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('truck_no', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('plant_address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_name', models.CharField(max_length=100)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckTransactionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_no', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateField(null=True)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transporter', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_per_ton', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('deliver_point', models.CharField(blank=True, max_length=100, null=True)),
                ('truck_weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TruckTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_no', models.CharField(max_length=50)),
                ('transaction_date', models.DateField()),
                ('city_name', models.CharField(max_length=100)),
                ('transporter', models.CharField(max_length=100)),
                ('amount_per_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('truck_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_point', models.CharField(max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('check_in_status', models.IntegerField(default=0)),
                ('check_out_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TruckTransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_slip_no', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('freight', models.CharField(blank=True, max_length=50, null=True)),
                ('check_in_status', models.IntegerField(default=0)),
                ('check_out_status', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.plantmaster')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.trucktransactionmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('check_in', models.CharField(blank=True, max_length=50, null=True)),
                ('check_out', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.trucklocation')),
            ],
        ),
        migrations.CreateModel(
            name='LoadingShiftingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('plant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('loading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.loadingmaster')),
            ],
        ),
        migrations.CreateModel(
            name='LoadingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('loading_slip_no', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('priority', models.IntegerField(null=True)),
                ('freight', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.trucktransactions')),
            ],
        ),
    ]
